# Generated by Django 3.0 on 2019-12-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cook', '0002_auto_20191211_0815'),
        ('item', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cook.Cook'),
        ),
        migrations.AddField(
            model_name='dish',
            name='items',
            field=models.ManyToManyField(blank=True, to='item.Item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurants',
            field=models.ManyToManyField(to='restaurant.Restaurant'),
        ),
    ]
