# Generated by Django 2.2.7 on 2019-12-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('ratings', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating'),
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='items',
            field=models.ManyToManyField(blank=True, to='item.Item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurants',
            field=models.ManyToManyField(to='restaurant.Restaurant'),
        ),
    ]
