# Generated by Django 2.2.7 on 2019-11-25 20:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20191125_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating'),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant'),
        ),
    ]
