# Generated by Django 2.2.7 on 2019-12-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20191207_1616'),
        ('item', '0002_auto_20191205_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating'),
        ),
    ]
