# Generated by Django 2.2.7 on 2019-11-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20191126_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating'),
        ),
    ]
