# Generated by Django 2.2.7 on 2019-12-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('VISITOR', 'Visitor'), ('REGISTERED', 'Registered'), ('VIP', 'VIP')], default='VISITOR', max_length=11)),
                ('first_name', models.CharField(blank=True, default='', max_length=20)),
                ('last_name', models.CharField(blank=True, default='', max_length=20)),
                ('customer_email', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
