# Generated by Django 2.2.7 on 2019-11-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Customer',
            fields=[
                ('visitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.Visitor')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=100)),
            ],
            bases=('customer.visitor',),
        ),
        migrations.CreateModel(
            name='VIP_Customer',
            fields=[
                ('registered_customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.Registered_Customer')),
                ('customer_status', models.CharField(max_length=10)),
            ],
            bases=('customer.registered_customer',),
        ),
    ]
