# Generated by Django 2.2.7 on 2019-11-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('customer', '0001_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.ManyToManyField(through='restaurant.Restaurant', to='ratings.Rating'),
        ),
    ]
