# Generated by Django 2.2.7 on 2019-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191125_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='restaurant_ratings',
            field=models.ManyToManyField(blank=True, to='ratings.Rating'),
        ),
    ]
