# Generated by Django 2.2.7 on 2019-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('REGISTERED', 'Registered'), ('VIP', 'VIP')], default='VISITOR', max_length=11),
        ),
    ]
