# Generated by Django 2.2.7 on 2019-12-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191208_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Preparing'), (3, 'Out for Delivery'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Rated')], default=1),
        ),
    ]
