# Generated by Django 2.2.7 on 2019-12-07 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_merge_20191206_1652'),
        ('item', '0002_auto_20191205_2051'),
        ('customer', '0003_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Preparing'), (3, 'Out for Delivery'), (4, 'Completed'), (5, 'Cancelled')], default=1)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 12, 7, 16, 0, 37, 306362, tzinfo=utc))),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2019, 12, 7, 16, 0, 37, 306391, tzinfo=utc))),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('dishes', models.ManyToManyField(to='item.Dish')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant')),
            ],
        ),
    ]
