# Generated by Django 2.2.7 on 2019-12-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20191208_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('REGISTERED', 'Registered'), ('VIP', 'VIP'), ('BLACKLISTED', 'Blacklisted')], default='VISITOR', max_length=11),
        ),
    ]
