# Generated by Django 2.2.7 on 2019-12-07 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 16, 0, 44, 315401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 16, 0, 44, 315428, tzinfo=utc)),
        ),
    ]
