# Generated by Django 2.2.7 on 2019-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20191210_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[(0, 'Visitor'), (1, 'Registered'), (2, 'VIP'), (3, 'Blacklisted')], default='VISITOR', max_length=11),
        ),
    ]
