# Generated by Django 2.2.7 on 2019-12-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20191207_1616'),
        ('customer', '0006_auto_20191207_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='restaurant_ratings',
        ),
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating'),
        ),
    ]
