# Generated by Django 2.2.7 on 2019-11-25 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('delivery_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='restaurant',
            field=models.ManyToManyField(null=True, to='restaurant.Restaurant'),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='warnings',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
