# Generated by Django 2.2.7 on 2019-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0002_auto_20191125_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='restaurant',
            field=models.ManyToManyField(to='restaurant.Restaurant'),
        ),
    ]
