# Generated by Django 2.2.7 on 2019-12-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0002_auto_20191207_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='rating',
        ),
    ]
