# Generated by Django 2.2.7 on 2019-12-08 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20191208_2320'),
        ('delivery_person', '0002_auto_20191208_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Order'),
        ),
    ]
