# Generated by Django 2.2.7 on 2019-12-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0002_auto_20191205_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Open To Bid'), (3, 'Active'), (4, 'Completed')], default=1),
        ),
    ]
