# Generated by Django 2.2.7 on 2019-11-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('delivery_person', '0003_auto_20191125_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant'),
        ),
    ]
