# Generated by Django 2.2.7 on 2019-12-09 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0003_delivery_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Order'),
        ),
    ]
