# Generated by Django 2.2.7 on 2019-12-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0003_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='who_delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_person.DeliveryPerson'),
        ),
    ]
