# Generated by Django 2.2.7 on 2019-11-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191125_0255'),
        ('ratings', '0002_rating_resturant'),
        ('delivery_person', '0004_auto_20191125_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.Rating')),
                ('to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('who_delivered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_person.DeliveryPerson')),
            ],
        ),
    ]
