# Generated by Django 2.2.7 on 2019-11-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0006_auto_20191125_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.Rating'),
        ),
    ]
