# Generated by Django 2.2.7 on 2019-11-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0007_auto_20191125_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
