# Generated by Django 2.2.7 on 2019-12-06 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_cost',
            field=models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
