# Generated by Django 2.2.7 on 2019-11-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('salesperson', '0002_auto_20191125_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=True, to='restaurant.Restaurant'),
        ),
    ]
