# Generated by Django 2.2.7 on 2019-11-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0003_salesperson_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='restaurant',
        ),
    ]
