# Generated by Django 2.2.7 on 2019-11-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('salesperson', '0004_remove_purchase_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant'),
        ),
    ]
