# Generated by Django 2.2.7 on 2019-12-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrating',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_person.Delivery'),
        ),
    ]
