# Generated by Django 2.2.7 on 2019-12-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191205_2056'),
        ('restaurant', '0002_auto_20191205_2043'),
    ]

    operations = [
    ]
