# Generated by Django 2.2.7 on 2019-11-25 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('cook', '0001_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating'),
        ),
        migrations.AddField(
            model_name='cook',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
