# Generated by Django 2.2.7 on 2019-11-25 02:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_auto_20191125_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.Rating'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='cook',
            name='warnings',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
