# Generated by Django 2.2.7 on 2019-11-25 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20191125_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.Rating'),
        ),
    ]
